name: add-jira-link-to-pr

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const keys = (context.payload.pull_request?.title || '').match(/[A-Z]{3,}-\d+/g) || [];
            if (!keys.length) return;
            const links = keys.map(key => `* [${key}](https://onetakeda.atlassian.net/browse/${key})`).join('')
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Jira links:**\n${links}`,
            });
